// This file is generated by crates/kibel-tools.
// Do not edit by hand.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResourceContract {
    pub name: &'static str,
    pub kind: &'static str,
    pub operation: &'static str,
    pub all_variables: &'static [&'static str],
    pub required_variables: &'static [&'static str],
    pub graphql_file: &'static str,
    pub client_method: &'static str,
    pub document: &'static str,
}

pub const RESOURCE_CONTRACT_VERSION: u32 = 1;
pub const RESOURCE_CONTRACT_UPSTREAM_COMMIT: &str = "";

pub const RESOURCE_CONTRACTS: &[ResourceContract] = &[
    ResourceContract {
        name: "searchNote",
        kind: "query",
        operation: "SearchNote",
        all_variables: &[
            "after",
            "before",
            "first",
            "last",
            "query",
            "resources",
            "coediting",
            "updated",
            "groupIds",
            "userIds",
            "folderIds",
            "likerIds",
            "isArchived",
            "sortBy",
        ],
        required_variables: &["query"],
        graphql_file: "endpoint:query.search",
        client_method: "search_note",
        document: "query SearchNote(
  $query: String!
  $resources: [SearchResourceKind!]
  $coediting: Boolean
  $updated: SearchDate
  $groupIds: [ID!]
  $userIds: [ID!]
  $folderIds: [ID!]
  $likerIds: [ID!]
  $isArchived: Boolean
  $sortBy: SearchSortKind
  $first: Int!
) {
  search(
    query: $query
    resources: $resources
    coediting: $coediting
    updated: $updated
    groupIds: $groupIds
    userIds: $userIds
    folderIds: $folderIds
    likerIds: $likerIds
    isArchived: $isArchived
    sortBy: $sortBy
    first: $first
  ) {
    edges {
      node {
        document {
          ... on Node {
            id
          }
        }
        title
        url
        contentSummaryHtml
        path
        author {
          account
          realName
        }
      }
    }
  }
}",
    },
    ResourceContract {
        name: "searchFolder",
        kind: "query",
        operation: "SearchFolder",
        all_variables: &["after", "before", "first", "last", "query"],
        required_variables: &["query"],
        graphql_file: "endpoint:query.searchFolder",
        client_method: "search_folder",
        document: "query SearchFolder($query: String!, $first: Int!) {
  searchFolder(query: $query, first: $first) {
    edges {
      node {
        name
        fixedPath
        group {
          name
          isPrivate
        }
      }
    }
  }
}",
    },
    ResourceContract {
        name: "getGroups",
        kind: "query",
        operation: "GetGroups",
        all_variables: &["after", "before", "first", "last", "ability"],
        required_variables: &[],
        graphql_file: "endpoint:query.groups",
        client_method: "get_groups",
        document: "query GetGroups($first: Int!) {
  groups(first: $first) {
    edges {
      node {
        id
        name
        isDefault
        isArchived
      }
    }
  }
}",
    },
    ResourceContract {
        name: "getFolders",
        kind: "query",
        operation: "GetFolders",
        all_variables: &[
            "after",
            "before",
            "first",
            "last",
            "parentFolderId",
            "parentFolderIds",
            "active",
        ],
        required_variables: &[],
        graphql_file: "endpoint:query.folders",
        client_method: "get_folders",
        document: "query GetFolders($first: Int!) {
  folders(first: $first) {
    edges {
      node {
        id
        name
      }
    }
  }
}",
    },
    ResourceContract {
        name: "getNotes",
        kind: "query",
        operation: "GetNotes",
        all_variables: &[
            "after", "before", "first", "last", "orderBy", "folderId", "active",
        ],
        required_variables: &[],
        graphql_file: "endpoint:query.notes",
        client_method: "get_notes",
        document: "query GetNotes($folderId: ID!, $first: Int!, $last: Int) {
  notes(folderId: $folderId, first: $first, last: $last) {
    edges {
      node {
        id
        title
        url
      }
    }
  }
}",
    },
    ResourceContract {
        name: "getNote",
        kind: "query",
        operation: "GetNote",
        all_variables: &["id"],
        required_variables: &["id"],
        graphql_file: "endpoint:query.note",
        client_method: "get_note",
        document: "query GetNote($id: ID!) {
  note(id: $id) {
    id
    title
    content
  }
}",
    },
    ResourceContract {
        name: "getNoteFromPath",
        kind: "query",
        operation: "GetNoteFromPath",
        all_variables: &["path"],
        required_variables: &["path"],
        graphql_file: "endpoint:query.noteFromPath",
        client_method: "get_note_from_path",
        document: "query GetNoteFromPath($path: String!, $first: Int!) {
  noteFromPath(path: $path) {
    id
    title
    content
    url
    author {
      account
      realName
    }
    folders(first: $first) {
      edges {
        node {
          id
          name
          fullName
          fixedPath
          group {
            id
            name
          }
        }
      }
    }
    comments(first: $first) {
      edges {
        node {
          id
          anchor
          content
          author {
            account
            realName
          }
          replies(first: $first) {
            edges {
              node {
                id
                anchor
                content
                author {
                  account
                  realName
                }
              }
            }
          }
        }
      }
    }
    inlineComments(first: $first) {
      edges {
        node {
          id
          anchor
          content
          author {
            account
            realName
          }
          replies(first: $first) {
            edges {
              node {
                id
                anchor
                content
                author {
                  account
                  realName
                }
              }
            }
          }
        }
      }
    }
  }
}",
    },
    ResourceContract {
        name: "getFolder",
        kind: "query",
        operation: "GetFolder",
        all_variables: &["id"],
        required_variables: &["id"],
        graphql_file: "endpoint:query.folder",
        client_method: "get_folder",
        document: "query GetFolder($id: ID!, $first: Int!) {
  folder(id: $id) {
    name
    fullName
    fixedPath
    createdAt
    updatedAt
    group {
      id
      name
    }
    folders(first: $first) {
      edges {
        node {
          id
          name
        }
      }
    }
    notes(first: $first) {
      edges {
        node {
          id
          title
        }
      }
    }
  }
}",
    },
    ResourceContract {
        name: "getFolderFromPath",
        kind: "query",
        operation: "GetFolderFromPath",
        all_variables: &["path"],
        required_variables: &["path"],
        graphql_file: "endpoint:query.folderFromPath",
        client_method: "get_folder_from_path",
        document: "query GetFolderFromPath($path: String!, $first: Int!) {
  folderFromPath(path: $path) {
    name
    fullName
    fixedPath
    createdAt
    updatedAt
    group {
      id
      name
    }
    folders(first: $first) {
      edges {
        node {
          id
          name
        }
      }
    }
    notes(first: $first) {
      edges {
        node {
          id
          title
        }
      }
    }
  }
}",
    },
    ResourceContract {
        name: "getFeedSections",
        kind: "query",
        operation: "GetFeedSections",
        all_variables: &["kind", "groupId", "first", "after"],
        required_variables: &["first"],
        graphql_file: "endpoint:query.feedSections",
        client_method: "get_feed_sections",
        document: "query GetFeedSections($kind: FeedKind!, $groupId: ID!, $first: Int!) {
  feedSections(kind: $kind, groupId: $groupId, first: $first) {
    edges {
      node {
        ... on FeedNote {
          date
          note {
            id
            title
            contentSummaryHtml
          }
        }
        ... on FeedFolderParcel {
          date
          folder {
            id
            name
          }
          notes(first: $first) {
            edges {
              node {
                id
                title
                contentSummaryHtml
              }
            }
          }
        }
        ... on FeedUserParcel {
          date
          user {
            account
            realName
          }
          notes(first: $first) {
            edges {
              node {
                id
                title
                contentSummaryHtml
              }
            }
          }
        }
      }
    }
  }
}",
    },
    ResourceContract {
        name: "createNote",
        kind: "mutation",
        operation: "CreateNote",
        all_variables: &["input"],
        required_variables: &["input"],
        graphql_file: "endpoint:mutation.createNote",
        client_method: "create_note",
        document: "mutation CreateNote($input: CreateNoteInput!) {
  createNote(input: $input) {
    clientMutationId
    note {
      id
      title
      content
    }
  }
}",
    },
    ResourceContract {
        name: "createComment",
        kind: "mutation",
        operation: "CreateComment",
        all_variables: &["input"],
        required_variables: &["input"],
        graphql_file: "endpoint:mutation.createComment",
        client_method: "create_comment",
        document: "mutation CreateComment($input: CreateCommentInput!) {
  createComment(input: $input) {
    comment {
      id
    }
  }
}",
    },
    ResourceContract {
        name: "createCommentReply",
        kind: "mutation",
        operation: "CreateCommentReply",
        all_variables: &["input"],
        required_variables: &["input"],
        graphql_file: "endpoint:mutation.createCommentReply",
        client_method: "create_comment_reply",
        document: "mutation CreateCommentReply($input: CreateCommentReplyInput!) {
  createCommentReply(input: $input) {
    reply {
      id
    }
  }
}",
    },
    ResourceContract {
        name: "createFolder",
        kind: "mutation",
        operation: "CreateFolder",
        all_variables: &["input"],
        required_variables: &["input"],
        graphql_file: "endpoint:mutation.createFolder",
        client_method: "create_folder",
        document: "mutation CreateFolder($input: CreateFolderInput!) {
  createFolder(input: $input) {
    folder {
      id
    }
  }
}",
    },
    ResourceContract {
        name: "moveNoteToAnotherFolder",
        kind: "mutation",
        operation: "MoveNoteToAnotherFolder",
        all_variables: &["input"],
        required_variables: &["input"],
        graphql_file: "endpoint:mutation.moveNoteToAnotherFolder",
        client_method: "move_note_to_another_folder",
        document: "mutation MoveNoteToAnotherFolder($input: MoveNoteToAnotherFolderInput!) {
  moveNoteToAnotherFolder(input: $input) {
    note {
      id
    }
  }
}",
    },
    ResourceContract {
        name: "attachNoteToFolder",
        kind: "mutation",
        operation: "AttachNoteToFolder",
        all_variables: &["input"],
        required_variables: &["input"],
        graphql_file: "endpoint:mutation.attachNoteToFolder",
        client_method: "attach_note_to_folder",
        document: "mutation AttachNoteToFolder($input: AttachNoteToFolderInput!) {
  attachNoteToFolder(input: $input) {
    note {
      id
    }
  }
}",
    },
    ResourceContract {
        name: "updateNoteContent",
        kind: "mutation",
        operation: "UpdateNoteContent",
        all_variables: &["input"],
        required_variables: &["input"],
        graphql_file: "endpoint:mutation.updateNoteContent",
        client_method: "update_note",
        document: "mutation UpdateNoteContent($input: UpdateNoteContentInput!) {
  updateNoteContent(input: $input) {
    note {
      id
      title
      content
    }
  }
}",
    },
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TrustedOperation {
    SearchNote,
    SearchFolder,
    GetGroups,
    GetFolders,
    GetNotes,
    GetNote,
    GetNoteFromPath,
    GetFolder,
    GetFolderFromPath,
    GetFeedSections,
    CreateNote,
    CreateComment,
    CreateCommentReply,
    CreateFolder,
    MoveNoteToAnotherFolder,
    AttachNoteToFolder,
    UpdateNoteContent,
}

pub const TRUSTED_OPERATIONS: &[TrustedOperation] = &[
    TrustedOperation::SearchNote,
    TrustedOperation::SearchFolder,
    TrustedOperation::GetGroups,
    TrustedOperation::GetFolders,
    TrustedOperation::GetNotes,
    TrustedOperation::GetNote,
    TrustedOperation::GetNoteFromPath,
    TrustedOperation::GetFolder,
    TrustedOperation::GetFolderFromPath,
    TrustedOperation::GetFeedSections,
    TrustedOperation::CreateNote,
    TrustedOperation::CreateComment,
    TrustedOperation::CreateCommentReply,
    TrustedOperation::CreateFolder,
    TrustedOperation::MoveNoteToAnotherFolder,
    TrustedOperation::AttachNoteToFolder,
    TrustedOperation::UpdateNoteContent,
];

pub const fn trusted_operation_contract_index(operation: TrustedOperation) -> usize {
    match operation {
        TrustedOperation::SearchNote => 0,
        TrustedOperation::SearchFolder => 1,
        TrustedOperation::GetGroups => 2,
        TrustedOperation::GetFolders => 3,
        TrustedOperation::GetNotes => 4,
        TrustedOperation::GetNote => 5,
        TrustedOperation::GetNoteFromPath => 6,
        TrustedOperation::GetFolder => 7,
        TrustedOperation::GetFolderFromPath => 8,
        TrustedOperation::GetFeedSections => 9,
        TrustedOperation::CreateNote => 10,
        TrustedOperation::CreateComment => 11,
        TrustedOperation::CreateCommentReply => 12,
        TrustedOperation::CreateFolder => 13,
        TrustedOperation::MoveNoteToAnotherFolder => 14,
        TrustedOperation::AttachNoteToFolder => 15,
        TrustedOperation::UpdateNoteContent => 16,
    }
}

pub fn trusted_operation_contract(operation: TrustedOperation) -> &'static ResourceContract {
    &RESOURCE_CONTRACTS[trusted_operation_contract_index(operation)]
}
