// This file is generated by crates/kibel-tools.
// Do not edit by hand.

pub const CREATE_NOTE_INPUT_FIELDS: &[&str] = &[
    "clientMutationId",
    "title",
    "content",
    "draft",
    "coediting",
    "groupIds",
    "folders",
    "authorId",
    "publishedAt",
];

pub const CREATE_NOTE_PAYLOAD_FIELDS: &[&str] = &["clientMutationId", "note"];

pub const CREATE_NOTE_NOTE_PROJECTION_FIELDS: &[&str] = &["id", "title", "content", "url"];
